# Generated by Django 3.1.4 on 2020-12-19 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewLedger',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', webapp.models.TruncatingCharField(max_length=50)),
                ('primary_contact', webapp.models.TruncatingCharField(max_length=13)),
                ('secondary_contact', webapp.models.TruncatingCharField(blank=True, max_length=13)),
                ('address', webapp.models.TruncatingCharField(max_length=50)),
                ('remark', webapp.models.TruncatingCharField(max_length=50)),
                ('acc_status', models.BooleanField(default=True)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('pending_amount', models.PositiveIntegerField(default=0)),
                ('recieved_amount', models.PositiveIntegerField(default=0)),
                ('temp_pending', models.PositiveIntegerField(default=0)),
                ('temp_extra', models.PositiveIntegerField(default=0)),
                ('monthly_installment', models.PositiveIntegerField(default=0)),
                ('installment_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='SubLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', webapp.models.TruncatingCharField(max_length=50)),
                ('account_number', webapp.models.TruncatingCharField(max_length=12)),
                ('opening_date', webapp.models.TruncatingCharField(max_length=12)),
                ('closing_date', webapp.models.TruncatingCharField(max_length=12)),
                ('installment', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('new_ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.newledger')),
            ],
            options={
                'ordering': ['new_ledger_id'],
            },
        ),
        migrations.CreateModel(
            name='MakeReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_payment', models.PositiveIntegerField()),
                ('receipt_date', models.DateField(default=datetime.date.today)),
                ('remark', webapp.models.TruncatingCharField(blank=True, default=None, max_length=50)),
                ('ledger_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.newledger')),
            ],
            options={
                'ordering': ['receipt_date'],
            },
        ),
    ]
